name: demigames
main: com.demigodsrpg.demigames.
version: ${project.version}
description: Behind the scenes plugin for handling mini-games.
authors: [Asecta, HmmmQuestionMark]
softdepend: [Chitchat]
commands:
  ## Everyday Commands
  demigames:
    usage: /demigames
permisions:
  demigames.admin:
    default: op
