name: demigames
main: com.demigodsrpg.demigames.impl.Demigames
version: ${project.version}
description: ${project.description}
authors: [Asecta, HmmmQuestionMark, janie177]
softdepend: [Chitchat]
commands:
  ## Everyday Commands
  demigames:
    usage: /demigames
  joingame:
    usage: /joingame <name>
    alias: [join]
  leavegame:
    usage: /leavegame
    alias: [leave]
  createkit:
    usage: /createkit <name>
  applykit:
    usage: /applykit <name>
  createlocation:
    usage: /createlocation <name>
  createsign:
    usage: /createsign <name> <command...>
permisions:
  demigames.admin:
    default: op
