name: demigames
main: com.demigodsrpg.demigames.impl.DemigamesPlugin
version: ${project.version}
description: ${project.description}
authors: [Asecta, HmmmQuestionMark]
softdepend: [Chitchat]
commands:
  ## Everyday Commands
  demigames:
    usage: /demigames
permisions:
  demigames.admin:
    default: op
