name: demigames
main: com.demigodsrpg.demigames.impl.Demigames
version: ${project.version}
description: ${project.description}
authors: [Asecta, HmmmQuestionMark]
softdepend: [Chitchat]
commands:
  ## Everyday Commands
  demigames:
    usage: /demigames
  createkit:
    usage: /createkit <kit>
  applykit:
    usage: /applykit <kit>
permisions:
  demigames.admin:
    default: op
