name: demigames
main: com.demigodsrpg.demigames.game.Backend
version: ${project.version}
description: ${project.description}
authors: [Asecta, HmmmQuestionMark, janie177]
softdepend: [Chitchat]
commands:
  ## Everyday Commands
  demigames:
    usage: /demigames
  sessioninfo:
    usage: /sessioninfo <game> [sessionid]
  joingame:
    usage: /joingame <name>
    aliases: [join]
  leavegame:
    usage: /leavegame
    aliases: [leave]
  createkit:
    usage: /createkit <name>
  applykit:
    usage: /applykit <name>
  createlocation:
    usage: /createlocation <name>
  createsign:
    usage: /createsign <name> <command...>
permisions:
  demigames.admin:
    default: op
